version: '2'

services:
  site:
    image: docker.matchbooklab.com/sunrise2018/site
    restart: always
    networks:
      - default
      - proxy # only the container that interfaces with the proxy needs this
    environment:
      VIRTUAL_HOST: sunrise2018.org
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: sunrise2018.org
      LETSENCRYPT_EMAIL: cam@cameronspear.com

#  placeholder:
#    restart: always
#    build:
#      context: ./landing/
#    networks:
#      - default
#      - proxy # only the container that interfaces with the proxy needs this
#    environment:
#      VIRTUAL_HOST: sunrise2018.org
#      VIRTUAL_PORT: 80
#      LETSENCRYPT_HOST: sunrise2018.org
#      LETSENCRYPT_EMAIL: cam@cameronspear.com


networks:
  default:
  proxy:
    external:
      name: pandora_proxy
